### ISSUE TITLE
#code: .idea?

### ISSUE THREAD

**Issue by SqueezyDough** [sarkis1997/frontend-applications#7]
Het is me niet helemaal duidelijk wat deze files doen. Miss in je wiki duidelijke verwijzing met uitleg

**Comment by sarkis1997** [comment]
The .idea folder (hidden on OS X) in the solution root contains IntelliJ’s project specific settings files. These include per-project details such as VCS mapping and run and debug configurations, as well as per-user details, such as currently open files, navigation history and currently selected configuration.
